php:
   container_name: web_php
   image: tutum/apache-php
   environment:
     - ALLOW_OVERRIDE=true
   ports:
     - "9900:80"
   links:
     - db
   volumes:
     - ./web:/var/www
     - ./config/apache/apache2.conf:/etc/apache2/apache2.conf

db:
  container_name: web_db
  image: mariadb
  restart: always
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: admin
    MYSQL_PASSWORD: test
    MYSQL_DATABASE: database
  ports:
    - "9902:3306"

phpmyadmin:
  container_name: web_pma
  image: phpmyadmin/phpmyadmin:latest
  links:
    - db
  ports:
    - 9901:80
  environment:
    MYSQL_USER: admin
    MYSQL_PASSWORD: test
    MYSQL_DATABASE: database
